/**
 * ZeroLu プロンプト説明文の日本語翻訳マッピング
 * タイトル（英語）→ 説明文（日本語）
 *
 * Source: https://github.com/ZeroLu/awesome-nanobanana-pro
 * Total: 70 prompts
 */
export const ZEROLU_DESCRIPTIONS_JA: Record<string, string> = {
  "Hyper-Realistic Crowd Composition": "複数の著名人と特定の照明を使った複雑な構図を処理する",
  "2000s Mirror Selfie": "フラッシュ撮影とノスタルジックな要素で本格的な2000年代初頭の美学を生成する構造化JSONプロンプト",
  "Victoria's Secret Style Photoshoot": "精巧なディテールでハイグラマーなバックステージ風ファッション写真を作成するのに最適",
  "1990s Camera Style Portrait": "特定のフィルムテクスチャ、フラッシュ撮影、時代特有の雰囲気を再現するモデルの能力をテスト",
  "One-Click Business Photo (Silicon Valley Style)": "特定のレンズと照明の指示を使用して、カジュアルな写真をプロフェッショナルなスタジオヘッドショットに変換",
  "Emotional Film Photography": "顔の一貫性を保ちながら、映画的でノスタルジックな「Kodak Portra」ルックを作成",
  "Professional Headshot Creator": "自撮りからプロフェッショナルなプロフィール写真を作成",
  "Hyperrealistic Anime Portrait in Spotlight": "ドラマチックな照明のハイパーリアリスティックなアニメスタイルのポートレート",
  "Bathroom Mirror Selfie": "特定のスタイリングと構図で率直な鏡自撮りを作成",
  "Chalkboard Anime Art Documentation": "黒板のアニメ絵のフォトリアリスティックなドキュメンテーション",
  "Portrait with Puppy in Snow": "子犬との冬のポートレートを作成",
  "Fisheye Movie Character Selfie": "映画キャラクターとの360度自撮り",
  "Character Consistency Selfie with Movie Character": "あなたの特徴を保ちながら映画キャラクターとの自撮りを撮る",
  "Museum Art Exhibition Selfie": "クラシックな油絵との商業グレードの写真",
  "Compact Camera Screen Display": "コンパクトデジタルカメラの画面に表示された写真",
  "Magazine Cover Portrait": "光沢のある雑誌の表紙を作成",
  "Luxury Product Photography": "浮遊する高級商品のショットを作成",
  "Star Wars \"Where's Waldo\"": "密集した群衆と特定のキャラクター認識を処理するモデルの能力をテストする複雑なプロンプト",
  "Aging Through the Years": "単一の被写体における時間的一貫性と老化効果を実証",
  "Recursive Visuals": "無限ループロジック（ドロステ効果）を処理するモデルの能力を実証",
  "Coordinate Visualization": "緯度経度座標のみに基づいて特定の場所と時間を生成",
  "Conceptual Visualization": "特定のグループ（エンジニア）がランドマークをどのように視覚化するかの解釈的レンダリング",
  "Literal Interpretation": "ファイル名を視覚的な主題として解釈",
  "Multi-Subject Compositing": "複数の入力ポートレートを特定の表情を持つ単一の一貫したグループ写真に結合",
  "Whiteboard Marker Art": "ガラステクスチャ上の特定の描画メディア（色あせたマーカー）をシミュレート",
  "Split View 3D Render - iPhone 17 Pro": "リアルな左半分とワイヤーフレームの右半分を持つ3Dレンダリングを作成",
  "USA 3D Diorama with Landmarks": "米国のランドマークのアイソメトリック3Dジオラマを作成",
  "US Map Made of Famous Foods": "有名な食べ物で作られた米国の州の地図を作成",
  "City's Tallest Buildings 3D Cartoon View": "都市の最も高い建物のミニチュア3Dビューを作成",
  "3D Isometric Home Office Illustration": "ホームオフィスの3Dアイソメトリックビューを作成",
  "Emoji Combination - Banana with Sunglasses": "Googleスタイルのデザインで絵文字を組み合わせる",
  "Torn Paper Art Effect": "画像の特定の領域に破れた紙の効果を追加",
  "Cinematic Keyframe Generator": "参照画像から映画的なキーフレームとストーリーボードを生成",
  "Photo Book Style Magazine Cover with Coordinates": "9:16のアスペクト比を正確な座標で完全に活用した美しいフォトブックスタイルの雑誌カバー",
  "Floating Country Island Diorama": "特定の国の形をした浮遊するミニチュア島のハイパーリアリスティックなデジタルポスター",
  "Novel Scene 3D Poster": "ミニチュアジオラマ効果を持つ小説や映画の3Dポスターデザイン",
  "Miniature Swimming Pool Diorama": "特大のコンテナをプールとして特徴付けるシュールなミニチュアワールドコラージュポスター",
  "Christmas Ornament 3D Character": "クリスマスオーナメントの中のかわいい3Dキャラクターに変身",
  "Ironing Out Wrinkles": "ミニチュアアイロンでシワを滑らかにするアンチエイジングのシュールな解釈",
  "Perfectly Isometric Photography": "たまたま完璧にアイソメトリックである撮影写真を作成",
  "Extreme Wide Angle Phone Screen Replacement": "極端な広角とスマホ画面の置き換えで写真を編集",
  "Shop Window Cartoon Reflection": "ショーウィンドウの横に立つ人と、その漫画版を示す写真を作成",
  "Urban 3D LED Display": "都市環境における大型L字型3D LEDスクリーンのシーンを作成",
  "Trans-Dimensional Liquid Pour": "物理世界から液体がデジタルスクリーンに注ぎ込まれるシュールなシーン",
  "Fisheye Matcha Girl": "抹茶ドリンクを飲む女の子の超広角魚眼写真",
  "Canon IXUS Aesthetic Portrait": "Canon IXUSポイント＆シュートカメラの美学でポートレートを作成",
  "Hyperrealistic Anime Portrait Spotlight": "ドラマチックなスポットライトを使ったハイパーリアリスティックなアニメスタイルのポートレート",
  "Concept Visualization (Text to Infographic)": "テキストコンセプトを明確で教育的なベクターイラストに変換",
  "Kids' Crayon Travel Journal Illustrator": "都市の子供らしい旅行日記のイラストを生成",
  "Financial Sankey Diagram Visualization": "プロフェッショナルな財務サンキーダイアグラムを作成",
  "Virtual Model Try-On": "生地のテクスチャと照明の統合を保ちながら、モデルに特定の衣服を着せる",
  "Professional Product Photography": "乱雑な背景から商品を分離し、高級商業スタジオの設定に配置",
  "3D Chibi-Style Miniature Brand Store": "ブランドのミニチュア3Dストアを作成",
  "Room Furnishing Visualization": "空の部屋で家具がどのように見えるかを視覚化",
  "Hand-drawn Flowchart to Corporate Charts": "ホワイトボードのスケッチを明確な「マッキンゼースタイル」のベクタープレゼンテーションに変換",
  "UI Hand-drawn Sketch to High-Fidelity Prototype": "ワイヤーフレームの落書きをリアルなモバイルアプリのモックアップに変換",
  "Magazine Layout Generator": "複雑なタイポグラフィで印刷形式の記事を視覚化するのに最適",
  "Composition Rescue (Smart Outpainting)": "一致する景色をインテリジェントに生成して画像比率（例：16:9）を拡大",
  "Smart Crowd Removal": "背景から不要な人物を削除し、論理的なテクスチャでスペースを埋める",
  "Face Detection CCTV Simulation": "顔検出を備えた高角度CCTV監視ショットを作成",
  "Hard Furnishing Preview (Floor Plan to Design)": "シンプルな2Dマップからパースビューと3D平面図を含む完全なデザインプレゼンテーションボードを生成",
  "Viral Cover Image (Youtube/Douyin/TikTok)": "テキストオーバーレイ、誇張された表情、明るいグラフィックスで魅力的なサムネイルを作成",
  "Commercial Promotional Poster": "統合されたテキストと高品質な商品写真を使用したプロフェッショナルなセールスポスターをデザイン",
  "Physical Store/Travel Translation": "元の表面テクスチャ（壁、紙、油汚れ）を保ちながらメニューや看板を翻訳",
  "Digital Content Localization (Comics/Memes)": "テキストバブルをスクラビングし、一致するフォントでコンテンツを置き換えることで漫画やミームを翻訳",
  "3D Blind Box Style Avatar": "ポートレートをかわいいC4Dスタイルの「Pop Mart」おもちゃキャラクターに変換",
  "Pet Meme Creation": "ペットの写真をミニマリストで手描きの面白いステッカーに変換",
  "Y2K Scrapbook Poster with Multiple Poses": "複数のポーズを持つY2Kスタイルのスクラップブックポスターを作成",
  "Japanese High School Student Snap Photo": "日本の高校生のスタイルでスナップショットを作成",
  "AI Skin Analysis and Skincare Routine": "肌を分析してルーティンの推奨事項を提供",
};
